name: Code style

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  pint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    name: Pint

    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Setup PHP
        uses: shivammathur/setup-php@b604ade2a87db23f8871b7182e69ec5e75effb45 # v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress

      - name: Run Pint
        run: vendor/bin/pint --test

  assets:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    name: Frontend assets

    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Verify committed assets
        run: git diff --exit-code -- dist
